stages:
  - compile
  - test
  - deploy

build:
  stage: compile
  image: golang:latest
  script:
    - go get -d -v
    - go build -o bin/golang-gin-poc -v .

test:
  stage: test
  image: golang:latest
  script:
    - go test service/*.go

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=pragmatic-video-app --api-key=$HEROKU_API_KEY
  environment:
    name: Staging
    url: https://pragmatic-video-app.herokuapp.com/
  only:
    - gorm
